### ISSUE TITLE
Make a new release please

### ISSUE THREAD

**Issue by puiterwijk** [jmflinuxtx/kerneltest-harness#24]
Please roll a new release and put that into the Fedora Infra repo.
The latest release in the repo does not even contain the fix from fde7fe5b4ffe67b6d9557abc056334ac927fe634, so is quite old.

**Comment by pypingou** [comment]
Fixed in https://github.com/jmflinuxtx/kerneltest-harness/commit/213005cb8db0490d6ddb5e80dd4352abe9ecb82e
